apiVersion: v1
kind: Service
metadata:
  name: {{ include "embedding-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "embedding-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "embedding-server.selectorLabels" . | nindent 4 }}
