apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ required "global.miniRootUser must be set at install time" .Values.global.miniRootUser }}
  root-password: {{ required "global.miniRootPassword must be set at install time" .Values.global.miniRootPassword }}
