apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "global.keycloakAdminPassword must be set at install time" .Values.global.keycloakAdminPassword }}
