apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
