"""Agent-related API endpoints."""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.checkpoint.base import CheckpointTuple
from sqlalchemy.orm import Session

from app.agents.checkpointer import SqlAlchemyCheckpointSaver
from app.api.chat_http import refused_admission_response, reply_fields
from app.api.schemas import (
    AvailableWorkflowListResponse,
    AvailableWorkflowResponse,
    ChatRequest,
    ChatResponse,
    ThreadHistoryResponse,
    ThreadListResponse,
    ThreadMessage,
    ThreadSummary,
)
from app.core.auth import get_current_user
from app.db.database import get_db
from app.db.models import utc_now
from app.guardrails.output_guardrail import filter_output
from app.repositories import ThreadRepository
from app.services.chat_turn_service import admit_chat_message, run_chat_turn
from app.services.guardrail_config_service import GuardrailConfig, resolve_guardrail_config
from app.services.workflow_service import (
    DEFAULT_WORKFLOW,
    is_available,
    list_available_workflows,
    resolve_active_workflow,
)

router = APIRouter(prefix="/api/agents", tags=["agents"])


@router.post("/chat", response_model=None)
async def chat(
    request: ChatRequest,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ChatResponse | JSONResponse:
    """Chat with the agent.

    Requires authentication via Keycloak bearer token.
    Streaming is deferred to a future phase.

    A client-supplied thread_id that doesn't belong to the caller is never
    trusted: ThreadRepository.get_or_create_owned silently mints a fresh
    thread instead, so a request always succeeds but never resumes or
    reveals another user's conversation.

    The input guardrail runs before any of that, and before the agent is
    built at all: a rejected message never reaches the LLM, never creates
    or touches a thread. Its 400 response carries both the stable
    machine-readable reason code (detail, unchanged shape from every other
    endpoint's error contract) and a human-readable message (message)
    generated by the guardrail itself -- the frontend prefers the latter so
    the two can never drift out of sync the way a hand-maintained,
    duplicate lookup table in the UI would. The output guardrail runs after
    the agent responds, sanitizing the response in place rather than
    rejecting it. Both guardrails' audit-log writes (on rejection and on
    redaction, respectively) live in app.services.chat_guardrail_service,
    alongside the rationale for each guardrail's trip behavior.

    Admission (rate limit, input guardrail) and the turn itself run through
    app.services.chat_turn_service, shared with the admin's draft test chat
    (issue #84) so both run under identical rules.

    The rate limit check (issue #25) runs before the guardrail check --
    it's the cheaper, more fundamental gate (protects resource consumption
    itself, not content), so a request that's about to be throttled never
    pays for guardrail regex evaluation. Trip is a 429 with a Retry-After
    header, keyed by the caller's own user_id from the validated JWT --
    never request input, the same identity source ThreadRepository uses
    for thread ownership. Unlike a guardrail rejection, a rate-limit trip
    is deliberately not audit-logged (see
    app.services.rate_limiter_service and docs/SECURITY.md's
    rate-limiting section): it's a high-frequency operational signal, not
    an individually compliance-relevant event.
    """
    admission = admit_chat_message(
        db, user_id=user["user_id"], message=request.message, now=utc_now()
    )
    if not admission.admitted:
        db.commit()  # a guardrail rejection's audit entry
        return refused_admission_response(admission)

    thread_repository = ThreadRepository(db)
    existing_thread = (
        thread_repository.get_by_id_for_user(request.thread_id, user["user_id"])
        if request.thread_id
        else None
    )
    if existing_thread is not None:
        thread = existing_thread
    else:
        # A new conversation binds to the requested workflow (issue #85). Only
        # a published workflow may be used - never a draft or an unknown name.
        requested_workflow = request.workflow or DEFAULT_WORKFLOW
        if not is_available(db, requested_workflow, now=utc_now()):
            return JSONResponse(
                status_code=400,
                content={
                    "detail": "workflow_not_available",
                    "message": f"The workflow {requested_workflow!r} is not available.",
                },
            )
        thread = thread_repository.get_or_create_owned(
            None, user["user_id"], workflow_name=requested_workflow
        )

    # The published version of the thread's workflow (issues #83, #85): an
    # admin's published edit is live from the next turn. An existing thread
    # keeps its bound workflow whatever the request asked for.
    outcome = await run_chat_turn(
        db,
        user=user,
        thread=thread,
        workflow=resolve_active_workflow(db, thread.workflow_name, now=utc_now()),
        message=request.message,
        guardrail_config=admission.guardrail_config,
        run_kind="production",
        now=utc_now(),
    )
    return ChatResponse(**reply_fields(outcome), workflow=thread.workflow_name)


@router.get("/workflows", response_model=AvailableWorkflowListResponse)
async def list_workflows(
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> AvailableWorkflowListResponse:
    """The published workflows a user can start a conversation with.

    User feature (issue #85): any signed-in user. Drafts and unpublished
    workflows are never listed, and every published workflow is offered to
    every user in v1 (no per-role restriction yet).
    """
    workflows = list_available_workflows(db, now=utc_now())
    db.commit()  # persists the one-time built-in sync on a fresh database
    return AvailableWorkflowListResponse(
        workflows=[
            AvailableWorkflowResponse(
                name=w.name, description=w.description, is_default=w.is_default
            )
            for w in workflows
        ]
    )


@router.get("/threads")
async def list_threads(
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ThreadListResponse:
    """List the authenticated user's conversation threads, most recent first."""
    threads = ThreadRepository(db).list_for_user(user["user_id"])
    return ThreadListResponse(
        threads=[
            ThreadSummary(
                id=t.id, workflow=t.workflow_name, created_at=t.created_at, updated_at=t.updated_at
            )
            for t in threads
        ]
    )


@router.get("/threads/{thread_id}")
async def get_thread_history(
    thread_id: str,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ThreadHistoryResponse:
    """Fetch one thread's message history.

    Returns 404 both when the thread doesn't exist and when it belongs to
    a different user - never 403, so a caller can't distinguish "not
    yours" from "doesn't exist" and probe for valid thread_ids.
    """
    thread = ThreadRepository(db).get_by_id_for_user(thread_id, user["user_id"])
    if thread is None:
        raise HTTPException(status_code=404, detail="Thread not found")

    checkpoint_tuple = SqlAlchemyCheckpointSaver(db).get_tuple(
        {"configurable": {"thread_id": thread.id}}
    )
    guardrail_config = resolve_guardrail_config(db)
    guarded_prompt_text = resolve_active_workflow(
        db, thread.workflow_name, now=utc_now()
    ).agent_definition.guarded_prompt_text
    messages = _render_messages(
        checkpoint_tuple, guardrail_config=guardrail_config, system_prompt=guarded_prompt_text
    )

    return ThreadHistoryResponse(id=thread.id, workflow=thread.workflow_name, messages=messages)


def _render_messages(
    checkpoint_tuple: CheckpointTuple | None,
    *,
    guardrail_config: GuardrailConfig,
    system_prompt: str | None,
) -> list[ThreadMessage]:
    """Map a checkpoint's stored LangChain messages to user/agent turns.

    Mirrors what ChatWindow already renders: only human and AI messages
    are shown, tool-call/tool-result messages are internal detail.

    Re-runs the output guardrail on every stored AI message before
    returning it. This is necessary, not defensive: LangGraph's
    checkpointer persists the agent step's raw response during ainvoke()
    (see app.workflows.primitives.build_agent_node), before
    app.api.agents.chat ever calls filter_agent_response -- that
    redaction is applied only to the
    in-memory value used for the immediate HTTP response and is never
    written back into graph state. Without re-filtering here, reopening a
    thread would return the original, unredacted text for a message the
    live chat response correctly redacted, silently defeating the output
    guardrail on every replay. Uses the pure filter_output directly, not
    filter_agent_response: this is a read path, not a new redaction event,
    so it must not write a fresh guardrail.output_redacted audit entry
    every time a thread happens to be viewed.
    """
    if checkpoint_tuple is None:
        return []

    stored_messages = checkpoint_tuple.checkpoint["channel_values"].get("messages", [])
    rendered: list[ThreadMessage] = []
    for message in stored_messages:
        if isinstance(message, HumanMessage):
            rendered.append(ThreadMessage(role="user", text=str(message.content)))
        elif isinstance(message, AIMessage) and message.content:
            text = str(message.content)
            if guardrail_config.output_enabled:
                text = filter_output(text, system_prompt=system_prompt).text
            rendered.append(ThreadMessage(role="agent", text=text))
    return rendered
