"""Agent-related API endpoints."""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.checkpoint.base import CheckpointTuple
from sqlalchemy.orm import Session

from app.agents.chat_agent import create_chat_agent
from app.agents.checkpointer import SqlAlchemyCheckpointSaver
from app.api.schemas import (
    ChatRequest,
    ChatResponse,
    ThreadHistoryResponse,
    ThreadListResponse,
    ThreadMessage,
    ThreadSummary,
)
from app.core.auth import get_current_user
from app.core.config import settings
from app.db.database import get_db
from app.db.models import utc_now
from app.guardrails.input_guardrail import GuardrailVerdict, check_input
from app.guardrails.output_guardrail import filter_output
from app.repositories import AuditLogRepository, ThreadRepository

router = APIRouter(prefix="/api/agents", tags=["agents"])


def _extract_text(content: str | list) -> str:
    """Extract plain text from an AIMessage's content.

    LangChain types AIMessage.content as str | list[str | dict] -- some
    providers return a list of content blocks (e.g. multi-part or
    provider-annotated responses) instead of a bare string. A plain str()
    on a list produces Python's repr syntax (e.g. "[{'type': 'text', ...}]"),
    which both defeats the output guardrail's text-based regexes and shows
    garbled output to the user, so list content is joined into its text
    parts instead of stringified as-is.
    """
    if isinstance(content, str):
        return content
    parts = []
    for block in content:
        if isinstance(block, str):
            parts.append(block)
        elif isinstance(block, dict) and isinstance(block.get("text"), str):
            parts.append(block["text"])
    return "".join(parts)


@router.post("/chat", response_model=None)
async def chat(
    request: ChatRequest,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ChatResponse | JSONResponse:
    """Chat with the agent.

    Requires authentication via Keycloak bearer token.
    Streaming is deferred to a future phase.

    A client-supplied thread_id that doesn't belong to the caller is never
    trusted: ThreadRepository.get_or_create_owned silently mints a fresh
    thread instead, so a request always succeeds but never resumes or
    reveals another user's conversation.

    The input guardrail runs before any of that, and before the agent is
    built at all: a rejected message never reaches the LLM, never creates
    or touches a thread, and is recorded as an audit event (see
    app.guardrails.input_guardrail for why reject, not sanitize or flag,
    is this guardrail's trip behavior). Its 400 response carries both the
    stable machine-readable reason code (detail, unchanged shape from
    every other endpoint's error contract) and a human-readable message
    (message) generated by the guardrail itself -- the frontend prefers
    the latter so the two can never drift out of sync the way a
    hand-maintained, duplicate lookup table in the UI would. The output
    guardrail runs after
    the agent responds, sanitizing the response in place rather than
    rejecting it (see app.guardrails.output_guardrail for why); a
    redaction is likewise a compliance-relevant event and is recorded,
    keyed by thread_id rather than the response text itself -- the
    redacted content is exactly what must not be written into an
    append-only, indefinitely-retained audit record.
    """
    guardrail_result = check_input(request.message)
    if guardrail_result.verdict == GuardrailVerdict.REJECTED:
        AuditLogRepository(db).record(
            actor_user_id=user["user_id"],
            action="guardrail.input_rejected",
            field_name="message",
            old_value=None,
            new_value=guardrail_result.reason,
            now=utc_now(),
        )
        db.commit()
        return JSONResponse(
            status_code=400,
            content={"detail": guardrail_result.reason, "message": guardrail_result.message},
        )

    thread_repository = ThreadRepository(db)
    thread = thread_repository.get_or_create_owned(request.thread_id, user["user_id"])

    agent = create_chat_agent(
        db=db,
        token=user["access_token"],
        mcp_url=settings.doc_search_mcp_url,
    )
    state = {
        "messages": [HumanMessage(content=request.message)],
        "thread_id": thread.id,
        "user_id": user["user_id"],
    }

    result = await agent.ainvoke(state, config={"configurable": {"thread_id": thread.id}})
    thread_repository.touch(thread.id, now=utc_now())
    db.commit()
    final_message = result["messages"][-1]

    filtered = filter_output(_extract_text(final_message.content))
    if filtered.was_modified:
        AuditLogRepository(db).record(
            actor_user_id=user["user_id"],
            action="guardrail.output_redacted",
            field_name="response",
            old_value=None,
            new_value=thread.id,
            now=utc_now(),
        )
        db.commit()

    return ChatResponse(response=filtered.text, thread_id=result["thread_id"])


@router.get("/threads")
async def list_threads(
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ThreadListResponse:
    """List the authenticated user's conversation threads, most recent first."""
    threads = ThreadRepository(db).list_for_user(user["user_id"])
    return ThreadListResponse(
        threads=[
            ThreadSummary(id=t.id, created_at=t.created_at, updated_at=t.updated_at)
            for t in threads
        ]
    )


@router.get("/threads/{thread_id}")
async def get_thread_history(
    thread_id: str,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ThreadHistoryResponse:
    """Fetch one thread's message history.

    Returns 404 both when the thread doesn't exist and when it belongs to
    a different user - never 403, so a caller can't distinguish "not
    yours" from "doesn't exist" and probe for valid thread_ids.
    """
    thread = ThreadRepository(db).get_by_id_for_user(thread_id, user["user_id"])
    if thread is None:
        raise HTTPException(status_code=404, detail="Thread not found")

    checkpoint_tuple = SqlAlchemyCheckpointSaver(db).get_tuple(
        {"configurable": {"thread_id": thread.id}}
    )
    messages = _render_messages(checkpoint_tuple)

    return ThreadHistoryResponse(id=thread.id, messages=messages)


def _render_messages(checkpoint_tuple: CheckpointTuple | None) -> list[ThreadMessage]:
    """Map a checkpoint's stored LangChain messages to user/agent turns.

    Mirrors what ChatWindow already renders: only human and AI messages
    are shown, tool-call/tool-result messages are internal detail.
    """
    if checkpoint_tuple is None:
        return []

    stored_messages = checkpoint_tuple.checkpoint["channel_values"].get("messages", [])
    rendered: list[ThreadMessage] = []
    for message in stored_messages:
        if isinstance(message, HumanMessage):
            rendered.append(ThreadMessage(role="user", text=str(message.content)))
        elif isinstance(message, AIMessage) and message.content:
            rendered.append(ThreadMessage(role="agent", text=str(message.content)))
    return rendered
